appName = "DebugTools"
appIcon = "../assets/logo.png"

strSend = "Send"
strSerialPort = "Port"
strSerialBaudrate = "Baudrate"
strSerialBytes = "DataBytes"
strSerialParity = "Parity"
strSerialStopbits = "Stopbits"
strAscii = "ASCII"
strHex = "HEX"
strSendSettings = "Send Settings"
strReceiveSettings = "Receive Settings"
strOpen = "Open"
strAutoLinefeed = "Auto\nLinefeed\n(ms)"
strAutoLinefeedTime = "200"
strScheduled = "Scheduled\nSend(ms)"
strScheduledTime = "300"
strSerialSettings = "Serial Settings"
strSerialReceiveSettings = "ReceiveSettings"
strSerialSendSettings = "Send Settings"

